server:
  port: 10051

# 服务名称
spring:
  application:
    name: zuulserver

eureka:
  client:
    # 注册中心地址，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    service-url:
      defaultZone: http://localhost:10050/eureka/
  instance:
    # 将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    prefer-ip-address: true


