server:
  port: 10050

eureka:
  instance:
    # server端的主机名
    hostname: localhost
  client:
    # 禁止将自己注册
    register-with-eureka: false
    # 屏蔽注册信息
    fetch-registry: false
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:10050/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka